# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

blank_issues_enabled: false
contact_links:
  - name: ğŸ“• Documentation Issue
    url: https://github.com/hashicorp/web-unified-docs
    about: Documentation has its own repository for all HashiCorp products and related issues or questions should be directed there
  - name: â“ Question
    url: https://discuss.hashicorp.com/c/terraform-core/cdk-for-terraform/47
    about: ğŸ™‹ For usage questions that may not require a core maintainer to answer, post in our community forum
  - name: HCP Terraform/Terraform Enterprise Troubleshooting
    url: https://support.hashicorp.com/hc/en-us/requests/new
    about: For issues related to the HCP Terraform/Terraform Enterprise platform, please submit a HashiCorp support request or email tf-cloud@hashicorp.support
