# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

blank_issues_enabled: false
contact_links:
  - name: ‚ùì Question
    url: https://discuss.hashicorp.com/c/terraform-core/cdk-for-terraform/47
    about: üôã For usage questions that may not require a core maintainer to answer, post in our community forum
  - name: Terraform Cloud/Enterprise Troubleshooting
    url: https://support.hashicorp.com/hc/en-us/requests/new
    about: For issues related to the Terraform Cloud/Enterprise platform, please submit a HashiCorp support request or email tf-cloud@hashicorp.support
