name: GitHub Actions Version Updater

on:
  schedule:
    # Every monday at 13:37 UTC
    - cron: 37 13 * * 1
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN_ACTIONS_UPDATER }}
      PR_TITLE: "chore: update github workflow actions"

    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
        with:
          token: ${{ secrets.GH_TOKEN_ACTIONS_UPDATER }}

      - name: Find and close older versions of this same PR
        run: |
          prlist=$(gh search prs --repo ${{ github.repository }} --state open --match title "$PR_TITLE" --json number --jq '.[].number')
          gh pr close -d --comment "Closing this because I'm about to open a newer PR." ${prlist}

      - name: Run GitHub Actions Version Updater
        uses: saadmk11/github-actions-version-updater@a7fd643bb3e9c1ef8f5c70bb5b645f5a2a9f395c
        with:
          token: ${{ secrets.GH_TOKEN_ACTIONS_UPDATER }}
          commit_message: ${{ env.PR_TITLE }}
          pull_request_title: ${{ env.PR_TITLE }}
          pull_request_team_reviewers: cdktf
          pull_request_labels: "dependencies"
          update_version_with: "release-commit-sha"
