name: "Pull Request Labeler"
on: [pull_request_target]

jobs:
  pr_ci_trigger:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@ba790c862c380240c6d5e7427be5ace9a05c754b # v4.0.3
        with:
          # The config file lives under .github/labeler.yml
          repo-token: "${{ secrets.PULL_REQUEST_LABELER }}"
          sync-labels: false # If set to true we could not easily overwrite it individually

  pr_size:
    runs-on: ubuntu-latest
    name: Label the PR size
    steps:
      - uses: codelytv/pr-size-labeler@v1.8.1 # TSCCR: no entry for repository "codelytv/pr-size-labeler"
        with:
          GITHUB_TOKEN: ${{ secrets.PULL_REQUEST_LABELER }}
          xs_label: "size/xs"
          xs_max_size: "10"
          s_label: "size/s"
          s_max_size: "100"
          m_label: "size/m"
          m_max_size: "500"
          l_label: "size/l"
          l_max_size: "1000"
          xl_label: "size/xl"
          fail_if_xl: "false"
          # Ignoring generate files
          files_to_ignore: "website/docs/cdktf/api-reference/csharp.mdx website/docs/cdktf/api-reference/go.mdx website/docs/cdktf/api-reference/java.mdx website/docs/cdktf/api-reference/python.mdx website/docs/cdktf/api-reference/typescript.mdx"
