name: checkrun-timechart
on:
  - pull_request

jobs:
  checkrun-timechart:
    runs-on: ubuntu-latest
    steps:
      - name: wait
        id: waitforstatuschecks
        uses: "WyriHaximus/github-action-wait-for-status@v1.7.1"
        with:
          ignoreActions: checkrun-timechart,update-snapshots-setup,update-snapshots-teardown,update-snapshots-linux,update-snapshots-windows,Vercel
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: checkrun-timechart
        uses: urcomputeringpal/checkrun-timechart-action@v0.0.6 # TSCCR: no entry for repository "urcomputeringpal/checkrun-timechart-action"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          SHA: "${{ github.event.pull_request.head.sha }}"
          TRACE_START: "${{ github.event.pull_request.updated_at }}"

      # It's difficult to determine all jobs for a PR
      # see https://docs.mergify.io/conditions/#about-status-checks
      # Since we have this 'checkrun-timechart' job, which essentially
      # knows all the statuses (see https://github.com/WyriHaximus/github-action-wait-for-status#output),
      # we can leverage it to provide a global status to mergify.
      - name: "mergify status"
        uses: actions/github-script@98814c53be79b1d30f795b907e553d8679345975 # v6.4.0
        if: ${{ steps.waitforstatuschecks.outputs.status != 'success' }}
        with:
          script: |
            core.setFailed('One of the Github Actions workflows failed for this PR')
